CXX = clang++
LDFLAGS = -stdlib=libc++ -std=c++11
OPTFLAGS = -O3 -g3
PEDANTRY = -Weverything -pedantic-errors -Werror -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-padded -Wno-missing-prototypes -Wmissing-declarations
PEDANTRY += -Wno-weak-vtables -Wno-global-constructors -Wno-exit-time-destructors -Wno-cast-align
CXXFLAGS = $(OPTFLAGS) -g3 -MMD -I/opt/local/include -std=c++11 -stdlib=libc++ -I/opt/local/include $(PEDANTRY)
