all: Wami.swf

Wami.swf:
	/usr/share/flexsdk/bin/mxmlc -compiler.source-path=src -static-link-runtime-shared-libraries=true -output ../html/Wami.swf src/edu/mit/csail/wami/client/Wami.mxml

.PHONY: Wami.swf
